# -*- coding: utf-8 -*-
"""
/***************************************************************************
 HVLSPMergePackages
                                 A QGIS plugin
 This plugin merge HVLSP Geopackage files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-30
        copyright            : (C) 2024 by IGN
        email                : guillaume.valtat@ign.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load HVLSPMergesPackages class from file HVLSPMergesPackages.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .HVLSP_merge_packages import HVLSPMergePackages
    return HVLSPMergePackages(iface)
