# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HVLSP_merge_packages_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HVLSPMergesPackagesDialogBase(object):
    def setupUi(self, HVLSPMergesPackagesDialogBase):
        HVLSPMergesPackagesDialogBase.setObjectName("HVLSPMergesPackagesDialogBase")
        HVLSPMergesPackagesDialogBase.resize(663, 301)
        self.button_box = QtWidgets.QDialogButtonBox(HVLSPMergesPackagesDialogBase)
        self.button_box.setGeometry(QtCore.QRect(450, 260, 201, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.toolButton = QtWidgets.QToolButton(HVLSPMergesPackagesDialogBase)
        self.toolButton.setGeometry(QtCore.QRect(10, 260, 61, 28))
        self.toolButton.setObjectName("toolButton")
        self.listWidget = QtWidgets.QListWidget(HVLSPMergesPackagesDialogBase)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 641, 241))
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(HVLSPMergesPackagesDialogBase)
        self.button_box.accepted.connect(HVLSPMergesPackagesDialogBase.accept)
        self.button_box.rejected.connect(HVLSPMergesPackagesDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(HVLSPMergesPackagesDialogBase)

    def retranslateUi(self, HVLSPMergesPackagesDialogBase):
        _translate = QtCore.QCoreApplication.translate
        HVLSPMergesPackagesDialogBase.setWindowTitle(_translate("HVLSPMergesPackagesDialogBase", "Select GeoPackage files"))
        self.toolButton.setText(_translate("HVLSPMergesPackagesDialogBase", "..."))
        self.listWidget.setSortingEnabled(True)
